//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Super_QOI_converter__Console_ {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Super_QOI_converter__Console_.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add at least one path.
        /// </summary>
        internal static string Add_at_least_one_path {
            get {
                return ResourceManager.GetString("Add at least one path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This path has already been entered, skipping....
        /// </summary>
        internal static string Already_entered {
            get {
                return ResourceManager.GetString("Already entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Command: &quot;Super QOI converter&quot; [Paths to files or folders] [Options].
        /// </summary>
        internal static string Commands_title {
            get {
                return ResourceManager.GetString("Commands title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The program received contradictory options (-c and -nc or -d and -nd at the same time). Delete one of those options and try again.
        /// </summary>
        internal static string Contradictory_options_error {
            get {
                return ResourceManager.GetString("Contradictory options error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -c
        ///	Copy attributes and dates from original files.
        /// </summary>
        internal static string Copy_attributes_and_dates_option {
            get {
                return ResourceManager.GetString("Copy attributes and dates option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -d
        ///	Delete original files when finishing.
        /// </summary>
        internal static string Delete_source_option {
            get {
                return ResourceManager.GetString("Delete source option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -no
        ///	Won&apos;t overwrite files and skip confirmation.
        /// </summary>
        internal static string Do_not_overwrite_option {
            get {
                return ResourceManager.GetString("Do not overwrite option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to copy attributes and dates (creation and modification date) from the original file?.
        /// </summary>
        internal static string Do_you_want_to_copy_file_info {
            get {
                return ResourceManager.GetString("Do you want to copy file info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete the original file?.
        /// </summary>
        internal static string Do_you_want_to_delete_original_file {
            get {
                return ResourceManager.GetString("Do you want to delete original file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Super QOI converter&quot; C:\Absolute\path\to\your\image.png
        ///&quot;Super QOI converter&quot; F:\Several\paths.jpg C:\At\the\same\time.bmp
        ///&quot;Super QOI converter&quot; C:\With\options.tif -c -d.
        /// </summary>
        internal static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File already exists. Overwrite?.
        /// </summary>
        internal static string File_already_exists {
            get {
                return ResourceManager.GetString("File already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -h, --help
        ///	Shows help.
        /// </summary>
        internal static string Help_option {
            get {
                return ResourceManager.GetString("Help option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Here are some examples:.
        /// </summary>
        internal static string Here_are_some_examples {
            get {
                return ResourceManager.GetString("Here are some examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -i
        ///	Ignore console colors.
        /// </summary>
        internal static string Ignore_colors_option {
            get {
                return ResourceManager.GetString("Ignore colors option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, that is an invalid option or an invalid path (you must use absolute paths).
        /// </summary>
        internal static string Invalid_option_or_path {
            get {
                return ResourceManager.GetString("Invalid option or path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It looks like {0} is a directory. Do you want to read each image from it?.
        /// </summary>
        internal static string It_looks_like_a_directory {
            get {
                return ResourceManager.GetString("It looks like a directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a made by.
        /// </summary>
        internal static string Made_by {
            get {
                return ResourceManager.GetString("Made by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a to get more info about how to execute this program by console parameters.
        /// </summary>
        internal static string More_info_how_to_execute {
            get {
                return ResourceManager.GetString("More info how to execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No to all.
        /// </summary>
        internal static string No_to_all {
            get {
                return ResourceManager.GetString("No to all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It&apos;s not necessary to use this program with console commands, you can execute it by double-clicking on the executable file and you&apos;ll receive help to use it as an usual program. However, if you want to use it as console command, here&apos;s the necessary info:.
        /// </summary>
        internal static string Not_console_necessary {
            get {
                return ResourceManager.GetString("Not console necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -nc
        ///	Won&apos;t copy attributes and dates from original files and will skip the confirmation message.
        /// </summary>
        internal static string Not_copy_attributes_and_dates_option {
            get {
                return ResourceManager.GetString("Not copy attributes and dates option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -nd
        ///	Won&apos;t delete original files and will skip the confirmation message.
        /// </summary>
        internal static string Not_delete_source_option {
            get {
                return ResourceManager.GetString("Not delete source option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This isn&apos;t a folder, image or it&apos;s not supported, skipping....
        /// </summary>
        internal static string Not_image_or_folder {
            get {
                return ResourceManager.GetString("Not image or folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -o
        ///	Overwrite files if they already exist.
        /// </summary>
        internal static string Overwrite_option {
            get {
                return ResourceManager.GetString("Overwrite option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Super QOI converter.
        /// </summary>
        internal static string Program_name {
            get {
                return ResourceManager.GetString("Program name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It isn&apos;t a valid path, skipping....
        /// </summary>
        internal static string Reading_invalid_path_message {
            get {
                return ResourceManager.GetString("Reading invalid path message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repository official link.
        /// </summary>
        internal static string Repo_official_link_message {
            get {
                return ResourceManager.GetString("Repo official link message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (console version).
        /// </summary>
        internal static string Specify_console_version {
            get {
                return ResourceManager.GetString("Specify console version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for use Super QOI converter!.
        /// </summary>
        internal static string Thank_you {
            get {
                return ResourceManager.GetString("Thank you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WARNING: This is going to delete the file PERMANENTLY. Won&apos;t move it to trash bin.
        /// </summary>
        internal static string This_is_going_to_delete_permanently {
            get {
                return ResourceManager.GetString("This is going to delete permanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a under a MIT license.
        /// </summary>
        internal static string Under_a_MIT_license {
            get {
                return ResourceManager.GetString("Under a MIT license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use arrows or numbers to select option and press Enter.
        /// </summary>
        internal static string Use_arrows_or_numbers_and_Enter {
            get {
                return ResourceManager.GetString("Use arrows or numbers and Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -v, --version
        ///	Shows the version of the program.
        /// </summary>
        internal static string Version_option {
            get {
                return ResourceManager.GetString("Version option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to.
        /// </summary>
        internal static string Welcome_to {
            get {
                return ResourceManager.GetString("Welcome to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With help of:.
        /// </summary>
        internal static string With_help_of {
            get {
                return ResourceManager.GetString("With help of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write your absolute paths now, one per line. Write &quot;Exit&quot; to continue:.
        /// </summary>
        internal static string Write_your_paths_now {
            get {
                return ResourceManager.GetString("Write your paths now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes to all.
        /// </summary>
        internal static string Yes_to_all {
            get {
                return ResourceManager.GetString("Yes to all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It looks like you didn&apos;t write any path, so the program will read them now.
        /// </summary>
        internal static string You_did_not_add_any_path {
            get {
                return ResourceManager.GetString("You did not add any path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must add path files to use these options!.
        /// </summary>
        internal static string You_must_add_paths {
            get {
                return ResourceManager.GetString("You must add paths", resourceCulture);
            }
        }
    }
}
